---
title: "Conducting Meta Analysis in R"
author: "Ekundayo Adeleke"
date: "2024-02-16"
output: html_document
---

This is a tutorial from [Deeply Trivial](https://www.deeplytrivial.com/2018/04/w-is-for-meta-analysis-weights.html) by Sara

```{r}
#Install packages
install.packages("metafor", dependencies = TRUE)

#install metafor with install.packages("metafor") if you haven't done so already
library(metafor)
```

```{r}
#data frame containing 11 studies that used continuous guilt rating as dependent variable
smd_meta<-data.frame(
  id = c("005","005","029","031","038","041","041","058","058","067","067"),
  study = c(1,2,3,1,1,1,2,1,2,1,2),
  author_year = c("Ruva 2007","Ruva 2007","Chrzanowski 2006","Studebaker 2000",
                  "Ruva 2008","Bradshaw 2007","Bradshaw 2007","Wilson 1998",
                  "Wilson 1998","Locatelli 2011","Locatelli 2011"),
  n1 = c(138,140,144,21,54,78,92,31,29,90,181),
  n2 = c(138,142,234,21,52,20,18,15,13,29,53),
  m1 = c(5.29,5.05,1.97,5.95,5.07,6.22,5.47,6.13,5.69,4.81,4.83),
  m2 = c(4.08,3.89,2.45,3.67,3.96,5.75,4.89,3.80,3.61,4.61,4.51),
  sd1 = c(1.65,1.50,1.08,1.02,1.65,2.53,2.31,2.51,2.51,1.20,1.19),
  sd2 = c(1.67,1.61,1.22,1.20,1.76,2.17,2.59,2.68,2.78,1.39,1.34)
)

#compute study effect sizes (standardized mean difference) and variances
smd_meta <- escalc(measure="SMD", m1i=m1, m2i=m2, sd1i=sd1, sd2i=sd2, n1i=n1,
                   n2i=n2,data=smd_meta)

#conduct fixed effects analysis and view output
smd.rma<-rma(yi,vi,method="FE",data=smd_meta)
summary(smd.rma)

#conduct random effects analysis
smd.rma.dl<-rma(yi,vi,method="DL",data=smd_meta)
summary(smd.rma.dl)
smd.rma.reml<-rma(yi,vi,method="REML",data=smd_meta)
summary(smd.rma.reml)

#custom function to compute prediction interval
predint<-function(x,pi) {
  alpha<-(1-(pi*.01))/2
  t<-abs(qt(alpha,(x$k-1)))
  sdp<-sqrt(x$se^2+x$tau2)
  lo<-x$b-(sdp*t)
  hi<-x$b+(sdp*t)
  paste(pi, "% prediction interval:", round(lo, digits=2), ",", round(hi,digits=2))
}

predint(smd.rma.reml,95)

#add study labels to random effects REML model
smd.rma.reml<-rma(yi,vi,method="REML",data=smd_meta,slab=paste(author_year,study,sep=" Study "))

#data visualizations
forest(smd.rma.reml)
funnel(smd.rma.reml)
```
